import { StyleSheet } from "react-native";

// export const lightGradient = ["#A3E4EC", "#C4F1F7", "#A3E4EC"] as const;
export const darkGradient = ["#0D1B2A", "#1B263B", "#415A77"] as const;
export const lightGradient = ["#0D1B2A", "#1B263B", "#415A77"] as const;

// export const lightTheme = StyleSheet.create({
//   background: {
//     flex: 1,
//   },
//   container: {
//     paddingVertical: 16,
//     paddingHorizontal: 10,
//     backgroundColor: "#F7FAFFA6",
//     borderWidth: 1,
//     borderColor: "#FFFFFFA4",
//     borderRadius: 20,
//     gap: 16,
//     shadowColor: "#FFFFFFA4",
//     shadowOffset: { width: 0, height: 2 },
//     shadowOpacity: 0.3,
//     shadowRadius: 6,
//     elevation: 4,
//     justifyContent: "center",
//     alignItems: "center",
//   },
//   textXl: {
//     fontSize: 22,
//     fontWeight: "bold",
//     textTransform: "uppercase",
//   },
//   textLg: {
//     fontSize: 22,
//   },
//   textSm: {
//     fontSize: 16,
//     fontWeight: "bold",
//   },
//   primary: {
//     color: "#5932EA",
//   },
//   secondary: {
//     color: "#364A5F",
//   },
//   popupText: {
//     color: "#FFFFFF",
//   },
//   popupBlue: {
//     backgroundColor: "#0F3DB4A6",
//     gap: 11,
//     justifyContent: "center",
//     alignItems: "center",
//     borderRadius: 100,
//     padding: 18,
//     width: "100%",
//   },
//   popupRed: {
//     backgroundColor: "#fa0f0fff",
//     gap: 11,
//     justifyContent: "center",
//     alignItems: "center",
//     borderRadius: 100,
//     padding: 18,
//     width: "100%",
//   },
//   popupGreen: {
//     backgroundColor: "#0FB40FA6",
//     gap: 11,
//     justifyContent: "center",
//     alignItems: "center",
//     borderRadius: 100,
//     padding: 18,
//     width: "100%",
//   },
//   popupYellow: {
//     backgroundColor: "#B4A90FA6",
//     gap: 11,
//     justifyContent: "center",
//     alignItems: "center",
//     borderRadius: 100,
//     padding: 18,
//     width: "100%",
//   },
//   btn: {
//     width: 262,
//     height: 89,
//     justifyContent: "center",
//     alignItems: "center",
//     borderRadius: 20,
//     fontSize: 22,
//     backgroundColor: "#5932EA",
//     borderWidth: 1,
//     borderColor: "#8CBFFF",
//     boxShadow: "0px 2px 6px #8CBFFFA4",
//   },
//   btnVersion: {
//     paddingVertical: 12,
//     paddingHorizontal: 16,
//     backgroundColor: "#FFFFFFA6",
//     justifyContent: "center",
//     alignItems: "center",
//     borderRadius: 100,
//     color: "#043B1A",
//   },
//   circleHeader: {
//     borderWidth: 4,
//     borderColor: "#F7FAFF",
//     borderRadius: 100,
//     width: 60,
//     height: 60,
//   },
//   input: {
//     borderWidth: 1,
//     borderColor: "#364A5F",
//     color: "#364A5F",
//     fontSize: 26,
//     borderRadius: 20,
//     width: "100%",
//     height: 78,
//     justifyContent: "center",
//     alignItems: "center",
//     textAlign: "center",
//     backgroundColor: "#F8FFFDA5",
//   },
//   tabBar: {
//     backgroundColor: "#FFFFFFA6",
//     flexDirection: "row",
//     justifyContent: "space-between",
//     borderRadius: 100,
//     padding: 16,
//     marginHorizontal: 16,
//     borderWidth: 1,
//     borderColor: "#FFFFFFA4",
//   },
//   borderTabletTime: {
//     paddingHorizontal: 12,
//     paddingVertical: 6,
//     borderWidth: 1,
//     borderColor: "#20558FFF",
//     borderRadius: 20,
//   },

//   item: {
//     padding: 10,
//     borderWidth: 1,
//     borderColor: "#364A5F",
//     borderRadius: 20,
//     flexDirection: "row",
//     justifyContent: "space-between",
//     alignItems: "center",
//     width: "100%",
//     backgroundColor: "#F8FFFDA5",
//   },
//   text: {
//     fontSize: 18,
//     color: "#59CECF",
//     width: "40%",
//   },
//   count: {
//     fontSize: 20,
//     color: "#59CECF",
//   },
//   btnItem: {
//     padding: 10,
//     backgroundColor: "#5932EA",
//     borderRadius: 10,
//     alignItems: "center",
//   },
// });
export const lightTheme = StyleSheet.create({
  background: {
    flex: 1,
  },
  container: {
    paddingVertical: 16,
    paddingHorizontal: 10,
    backgroundColor: "#115c6f5b",
    borderWidth: 1,
    borderColor: "#59CECFA4",
    borderRadius: 20,
    gap: 16,
    shadowColor: "#115C6FA4",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
    justifyContent: "center",
    alignItems: "center",
  },
  textXl: {
    fontSize: 22,
    fontWeight: "bold",
    textTransform: "uppercase",
  },
  textLg: {
    fontSize: 22,
  },
  textSm: {
    fontSize: 16,
    fontWeight: "bold",
  },
  primary: {
    color: "#59CECF",
  },
  secondary: {
    // color: "#59CECF",
        color: "#FFFFFF",
  },
  popupBlue: {
    backgroundColor: "#0F3DB4A6",
    gap: 11,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 100,
    padding: 18,
    width: "100%",
  },
  popupRed: {
    backgroundColor: "#fa0f0fff",
    gap: 11,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 100,
    padding: 18,
    width: "100%",
  },
  popupGreen: {
    backgroundColor: "#0FB40FA6",
    gap: 11,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 100,
    padding: 18,
    width: "100%",
  },
  popupYellow: {
    backgroundColor: "#B4A90FA6",
    gap: 11,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 100,
    padding: 18,
    width: "100%",
  },
  popupText: {
    color: "#59CECF",
  },
  btn: {
    width: 262,
    height: 56,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 20,
    fontSize: 18,
    backgroundColor: "#59CECF",
    zIndex: 10000,
  },
  btnVersion: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: "#59CECFA6",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 100,
    color: "#59CECF",
  },
  circleHeader: {
    borderWidth: 4,
    borderColor: "#59CECF",
    borderRadius: 100,
    width: 40,
    height: 40,
  },
  input: {
    borderWidth: 1,
    borderColor: "#59CECF",
    color: "#59CECF",
    fontSize: 26,
    borderRadius: 20,
    width: "100%",
    height: 78,
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    backgroundColor: "#115C6F",
  },
  tabBar: {
    backgroundColor: "#115C6F",
    borderRadius: 100,
    padding: 16,
    marginHorizontal: "5%",
    flexDirection: "row",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: "#59CECF",
    width: "90%",
    alignSelf: "center",
  },
  borderTabletTime: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: "#59CECF",
    borderRadius: 20,
  },
  item: {
    padding: 10,
    borderWidth: 1,
    borderColor: "#59CECF",
    borderRadius: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    backgroundColor: "#42454558",
  },
  text: {
    fontSize: 18,
    color: "#59CECF",
    width: "40%",
  },
  count: {
    fontSize: 20,
    color: "#59CECF",
  },
  btnItem: {
    padding: 10,
    backgroundColor: "#59CECF",
    borderRadius: 10,
    alignItems: "center",
  },
});
export const darkTheme = StyleSheet.create({
  background: {
    flex: 1,
  },
  container: {
    paddingVertical: 16,
    paddingHorizontal: 10,
    backgroundColor: "#115c6f5b",
    borderWidth: 1,
    borderColor: "#59CECFA4",
    borderRadius: 20,
    gap: 16,
    shadowColor: "#115C6FA4",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
    justifyContent: "center",
    alignItems: "center",
  },
  textXl: {
    fontSize: 22,
    fontWeight: "bold",
    textTransform: "uppercase",
  },
  textLg: {
    fontSize: 22,
  },
  textSm: {
    fontSize: 16,
    fontWeight: "bold",
  },
  primary: {
    color: "#59CECF",
  },
  secondary: {
    // color: "#59CECF",
        color: "#FFFFFF",
  },
  popupBlue: {
    backgroundColor: "#0F3DB4A6",
    gap: 11,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 100,
    padding: 18,
    width: "100%",
  },
  popupRed: {
    backgroundColor: "#fa0f0fff",
    gap: 11,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 100,
    padding: 18,
    width: "100%",
  },
  popupGreen: {
    backgroundColor: "#0FB40FA6",
    gap: 11,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 100,
    padding: 18,
    width: "100%",
  },
  popupYellow: {
    backgroundColor: "#B4A90FA6",
    gap: 11,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 100,
    padding: 18,
    width: "100%",
  },
  popupText: {
    color: "#59CECF",
  },
  btn: {
    width: 262,
    height: 56,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 20,
    fontSize: 18,
    backgroundColor: "#59CECF",
    zIndex: 10000,
  },
  btnVersion: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: "#59CECFA6",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 100,
    color: "#59CECF",
  },
  circleHeader: {
    borderWidth: 4,
    borderColor: "#59CECF",
    borderRadius: 100,
    width: 40,
    height: 40,
  },
  input: {
    borderWidth: 1,
    borderColor: "#59CECF",
    color: "#59CECF",
    fontSize: 26,
    borderRadius: 20,
    width: "100%",
    height: 78,
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    backgroundColor: "#115C6F",
  },
  tabBar: {
    backgroundColor: "#115C6F",
    borderRadius: 100,
    padding: 16,
    marginHorizontal: "5%",
    flexDirection: "row",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: "#59CECF",
    width: "90%",
    alignSelf: "center",
  },
  borderTabletTime: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: "#59CECF",
    borderRadius: 20,
  },
  item: {
    padding: 10,
    borderWidth: 1,
    borderColor: "#59CECF",
    borderRadius: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    backgroundColor: "#42454558",
  },
  text: {
    fontSize: 18,
    color: "#59CECF",
    width: "40%",
  },
  count: {
    fontSize: 20,
    color: "#59CECF",
  },
  btnItem: {
    padding: 10,
    backgroundColor: "#59CECF",
    borderRadius: 10,
    alignItems: "center",
  },
});
