import { StyleSheet } from "react-native";

export const lightGradient = ["#A3E4EC", "#C4F1F7", "#A3E4EC"] as const;
export const darkGradient = ["#0D1B2A", "#1B263B", "#415A77"] as const;

export const lightTheme = StyleSheet.create({
  background: {
    flex: 1,
  },
  container: {
    paddingVertical: 16,
    paddingHorizontal: 10,
    backgroundColor: "#F7FAFFA6",
    borderWidth: 1,
    borderColor: "#FFFFFFA4",
    borderRadius: 20,
    gap: 16,
    shadowColor: "#FFFFFFA4",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
    justifyContent: "center",
    alignItems: "center",
  },
  textXl: {
    fontSize: 22,
    fontWeight: "bold",
    textTransform: "uppercase",
  },
  textLg: {
    fontSize: 22,
  },
  textSm: {
    fontSize: 16,
    fontWeight: "bold",
  },
  primary: {
    color: "#5932EA",
  },
  secondary: {
    color: "#364A5F",
  },
  popupBlue: {
    color: "#0F3DB4A6",
    gap: 11,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 20,
  },
  popupRed: {
    color: "#B40F0FA6",
    gap: 11,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 20,
  },
  popupGreen: {
    color: "#0FB40FA6",
    gap: 11,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 20,
  },
  popupYellow: {
    color: "#B4A90FA6",
    gap: 11,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 20,
  },
  btn: {
    width: 262,
    height: 89,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 20,
    fontSize: 22,
    backgroundColor: "#5932EA",
    borderWidth: 1,
    borderColor: "#8CBFFF",
    boxShadow: "0px 2px 6px #8CBFFFA4",
  },
  btnVersion: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: "#FFFFFFA6",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 100,
    color: "#043B1A",
  },
  circleHeader: {
    borderWidth: 4,
    borderColor: "#F7FAFF",
    borderRadius: 100,
    width: 60,
    height: 60,
  },
  input: {
    borderWidth: 1,
    borderColor: "#364A5F",
    color: "#364A5F",
    fontSize: 26,
    borderRadius: 20,
    width: "100%",
    height: 78,
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    backgroundColor: "#F8FFFDA5",
  },
  tabBar: {
    backgroundColor: "#FFFFFFA6",
    flexDirection: "row",
    justifyContent: "space-between",
    borderRadius: 100,
    padding: 16,
    marginHorizontal: 16,
    borderWidth: 1,
    borderColor: "#FFFFFFA4",
  },
});

export const darkTheme = StyleSheet.create({
  background: {
    flex: 1,
  },
  container: {
    paddingVertical: 16,
    paddingHorizontal: 10,
    backgroundColor: "#115C6FA2",
    borderWidth: 1,
    borderColor: "#59CECFA4",
    borderRadius: 20,
    gap: 16,
    shadowColor: "#115C6FA4",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
    justifyContent: "center",
    alignItems: "center",
  },
  textXl: {
    fontSize: 22,
    fontWeight: "bold",
    textTransform: "uppercase",
  },
  textLg: {
    fontSize: 22,
  },
  textSm: {
    fontSize: 16,
    fontWeight: "bold",
  },
  primary: {
    color: "#59CECF",
  },
  secondary: {
    color: "#364A5F",
  },
  popupBlue: {
    color: "#0F3DB4A6",
    gap: 11,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 20,
  },
  popupRed: {
    color: "#B40F0FA6",
    gap: 11,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 20,
  },
  popupGreen: {
    color: "#0FB40FA6",
    gap: 11,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 20,
  },
  popupYellow: {
    color: "#B4A90FA6",
    gap: 11,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 20,
  },
  btn: {
    width: 262,
    height: 89,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 20,
    fontSize: 22,
    backgroundColor: "#59CECF",
  },
  btnVersion: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: "#59CECFA6",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 100,
    color: "#59CECF",
  },
  circleHeader: {
    borderWidth: 4,
    borderColor: "#59CECF",
    borderRadius: 100,
    width: 60,
    height: 60,
  },
  input: {
    borderWidth: 1,
    borderColor: "#59CECF",
    color: "#364A5F",
    fontSize: 26,
    borderRadius: 20,
    width: "100%",
    height: 78,
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    backgroundColor: "#FFFFFFA1",
  },
  tabBar: {
    backgroundColor: "#115C6FA2",
    borderRadius: 100,
    padding: 16,
    marginHorizontal: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: "#59CECF",
  },
});
